exports.config = {

  minMimosaVersion: "1.0.12"

  modules: ['lint', 'spritesmith']
  spritesmith:
    inDir: '../sprites'
    stylesheetOutDir: 'stylesheets'
    options:
      engine: 'gm'
      algorithm: 'binary-tree'
      json2css:
        format: 'stylus_hashtable'
        renamer: (name, spriteName) -> name
        templates:
          'stylus_hashtable': """
// Sprite {{options.spriteName}} auto generated by mimosa-spritesmith
${{options.spriteName}} = {
  image: '{{{items.0.escaped_image}}}',
  width: {{items.0.px.total_width}},
  height: {{items.0.px.total_height}},
  {{#items}}
  {{name}}: {{px.offset_x}} {{px.offset_y}} {{px.width}} {{px.height}},
  {{/items}}
  names: {{#items}}'{{name}}' {{/items}}
}
          """
  lint:
    rules:
      css:
        'zero-units': false    # json2css adds px units everywhere

}